### PR TITLE
include a variable to check if lang code was missing on initial page load

### PR DESCRIPTION
**Pull request by dohomi**
Hi @martinopic 

This is just a tiny helper but very important for my usecase, where I want to set the language based on Meteor.user()

### CODE REVIEW

**Comment by martinopic** [comment]
```dispatch``` (and ```missingLangCodeAction```) is not just called on initial page load so how do you know this is an initial page load? Is your use case that of #26  ? In this case I don't think is needed.

**Comment by dohomi** [comment]
In any case I would need the variable to check if there is an initial langKey set or if the user is entering the website without langKey. In our example app 

```
if (!langCode) {
      this.initalLangCodeMissing = true;
(...)
```
is a time safer and convenient way to see if the should be any ```Router.setLanguage()```calls or not

**Comment by mxab** [comment]
I think the problem if you have a the missingLangCode if the user opens for example "/" or "/dashboard", you first want to postpone the languageKey look/setting until the user is available. if the visitor of the page is not "loggingin" as there are not credentials available or the loggingin fails you want to continue with navigator lang or the default language.
if there is a langCode available which means the user called directly "/en" , "/de/dashboard" , "/it/la-random-article" you want to set the language to the langcode

i tried to model this in the missingLangCodeAction:
```

   missingLangCodeAction: function (path) {

//helper to set nav or default
        var setNavigatorLangOrDefault = function () {
          var lang;
          var navLang = navigator.language.split("-")[0];
          if (_.contains(languages, navLang)) {
            console.log("using nav", navLang);
            lang = navLang;
          } else {

            lang = Router.getDefaultLanguage();
            console.log("using default", lang);
          }
          Router.setLanguage(lang);
        };
//set language by user helper
        var setLanguageByUser = function () {
          console.log("setting user lanaguageKey", Meteor.user().languageKey);
          Router.setLanguage(Meteor.user().languageKey);
        };

//====================================================
// here starts the noLangCodeAction
        if (Meteor.loggingIn()) {

          console.log("user logging in");

          Tracker.autorun(function (c) {

            var logginIn = Meteor.loggingIn();
            if (!logginIn && Meteor.user()) {
              setLanguageByUser();
              c.stop();

            } else if (!logginIn) {
              console.log("finished loggingIn in but no user available");
              setNavigatorLangOrDefault()
              c.stop();
            } else {
              console.log("still logging in");// do not stop tracker
            }
          });

        } else if (Meteor.user()) {
          console.log("already logged in");
          setLanguageByUser();
          //Router.go("home");
        } else {

          setNavigatorLangOrDefault();
          //Router.go("home");
        }


      }
```

**Comment by martinopic** [comment]
This has been solved by introducing ```Router.getLangCode``` and ```Router.isLanguageSet``` methods in 0.5.2.

**Pull request closed without merging**
